### PR TITLE
Map fixes

### PR DESCRIPTION
**Pull request by brianbad**
A few changes - 
1. Addressed some more buggy map spots. This covers issue #32 .
2. Player can now swing his dagger by holding M for MELEE. This _**begins**_ to cover issue #40
     2.1. The hit-box is currently visible for testing. We need to come to a consensus on how the intersection 
            of the sword will be handled. Currently, the player's hit-box just extends in the current direction. The 
            main problem with this is in regards to 'up' and 'down', because the dagger doesn't actually extend 
            past the body of the sprite. Do we extend the hit-box in these instances or not?

### CODE REVIEW

**Comment by anand-bala** [comment]
@brianbad I can suggest a few possible fixes for 2.1. Tell me what you think.

1. Manually detect the collision, i.e., detect if there is a sprite in the direction of attack. This may not be the best option.
2. There is a animation for long sword. Check if that works. The only problem is that the whole sprite gets massive.
3. Create an invisible sprite for a weapon. This is easy and seems like the most straight forward approach. That way, the invisible animation can just be it moving forward and back. How does that work?

**Review by anand-bala — CHANGES_REQUESTED** [review]
Hey @brianbad . This looks great. But a few changes are required.

Change the Melee from a `Keyboard.isDown` to press. This is because the `isDown` requires that you hold it down to execute the complete thing. This sort of defeats the purpose of the

**Comment by brianbad** [comment]
@anand-bala In response to your comments regarding fixes for 2.1:
1. I'm not sure what you mean here. Detecting a direction of collision doesn't seem all that helpful when all of our current attacks are melee, and thus guaranteed to be close range anyway. I don't see how this would be any different then just extending the hit box, like I'm doing now. 
2. I really want to try and avoid this. Adding large weapons changes the constants required to read from the sprite sheet (and also probably animation index values) which would make animations for our object-model a complete mess, as each NPC would require different animation code depending on what weapon they have.
3. This seems most logical, but maybe not exactly easy. It would take some elbow grease to chisel this out, but I think this would be the best option.
           3.1. Regardless of all of this though, maybe we can continue on with my current (basic) method 
                 since we just need something working for the MVP. We can always come back later and tweak 
                 it (I think even our TA mentioned that this may be a good idea, ie. get attacking working, and 
                 then polish it up later).

Changes:
1. I actually kind of liked the fact that you hold the key instead of press it (it saves you from having to spam the key), but I could see why you could want it "One press = One attack". What does it defeat the purpose of though? It looks like your comment got cut off...

**Review by anand-bala — CHANGES_REQUESTED** [review]
There seems to be a bug. Check this out.

anim

**Reproducing the bug**:
1. While walking, hold down the `M` key.
2. Walk into the tree.

The bugs are:

1. The Animation is weird while moving and attacking (minor)
2. I can't move once I collide with the tree.

**Comment by anand-bala** [comment]
I will create a new branch named `combat`. Send this pull request there. That way, we don't pollute the `develop` branch.

**Comment by anand-bala** [comment]
We should implement a state machine for each `Entity`. And isolate all that within the `Entity` prototype. The idea is that an `Entity` should only be able to do certain things, say, while walking. I am posting a tutorial for this on Ryver.

**Pull request closed without merging**
