### PR TITLE
Navigation Mesh

### PR DESCRIPTION
**Pull request by jacobbel**
Added the navigation mesh to the new map. #65 
 Also disabled zooming.

### CODE REVIEW

**Comment by brianbad** [comment]
untitled
Wtf is wrong with this tree...?

**Comment by brianbad** [comment]
untitled1
... and this shoreline...?

**Comment by brianbad** [comment]
untitled2
Fuck is with this shore?

**Comment by brianbad** [comment]
untitled3
... and this one?

**Comment by brianbad** [comment]
untitled4
Bruh...

**Review by brianbad — DISMISSED** [review]
Refer to comments on Pull Request...

**Comment by sriram1996** [comment]
@brianbad i will fix those minor edges soon, theyre not terrible, gotta finish load first

**Review by sriram1996 — APPROVED** [review]

**Pull request merged**
