### PR TITLE
Factory feature added.

### PR DESCRIPTION
**Pull request by anand-bala**
The Factory for entities is complete. It generates a new Entity, places it on the map and adds it to a group. (Addresses issues #43, #38 )

I am generating 10 NPCs and Monsters are random locations on the map. I will have to add spawning points in the new map. 

I also dealt with Entities colliding with each other. Issue #31 

There are some bugs I introduced with collisions with other entities, mainly with rendering. Approach a monster or a woman from below.

### CODE REVIEW

**Review by brianbad — CHANGES_REQUESTED** [review]
It seems like you can't attack the NPC's (attack animation won't play). I suspect it's because when attacking, the hit-box extends and a collision occurs, and your collision handler isn't allowing a collision while (player.state === 'attacking'). Can you fix this?

**Comment by anand-bala** [comment]
@brianbad I fixed the issue you mentioned. Check it out now.

**Comment by brianbad** [comment]
@anand-bala That looks better! One more thing (Sorry I didn't catch it earlier) - Can you make it so that the player can't push NPC's through the blockLayer? Try pushing an NPC into a building or tree to see what I mean. The NPC shouldn't get pushed into the building/tree.

**Comment by anand-bala** [comment]
@brianbad, sorry for that, but just added a fix (I think...)

**Comment by brianbad** [comment]
@anand-bala  Thanks for fixing those two things! This looks like a good starting point for me to finish attacking and for Jake to get started with the AI.

**Review by brianbad — APPROVED** [review]

**Pull request merged**
